global:
  environment: local

components:
  load-generator:
    enabled: true
    imageOverride:
      repository: ghcr.io/open-telemetry/demo
      tag: latest-load-generator
    resources:
      requests:
        cpu: 550m
        memory: 2Gi
      limits:
        cpu: 1200m
        memory: 4Gi

  frontend:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi

  checkout:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
